version: "3.9"

services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      DEBUG: "True"
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./frontend/vue-project  # Путь до папки с Dockerfile для фронтенда
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/vue-project:/app  # Прокидываем исходный код
    command: npm run dev
