version: "3.9"

services:
  backend:
    build:
      context: .
    network_mode: "bridge"
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data  # Монтируем папку с данными
    command: >
      sh -c "
      python3 manage.py makemigrations movies &&
      python3 manage.py makemigrations users &&
      python3 manage.py migrate &&
      python3 manage.py import_movies &&
      python3 manage.py createsuperuser --no-input || true &&
      python3 manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=True
      - DATA_DIR=/app/data
      - DJANGO_SUPERUSER_USERNAME=Kira
      - DJANGO_SUPERUSER_EMAIL=Kira@example.com
      - DJANGO_SUPERUSER_PASSWORD=123456789Kira

  frontend:
    build:
      context: ./frontend/vue-project
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/vue-project:/app
      - /app/node_modules  # Исключаем node_modules
    command: npm run dev
